from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse
from starlette.datastructures import UploadFile

from app.core.container import get_container
from app.schemas.agent import (
    AgentChatRequest,
    AgentChatResponse,
    AgentExecuteRequest,
    AgentExecuteResponse,
)

router = APIRouter()


@router.post("/chat", response_model=AgentChatResponse)
def chat(payload: AgentChatRequest) -> AgentChatResponse:
    """将自然语言请求解析为结构化执行计划。
    Parse a natural-language request into a structured execution plan.
    """
    response = get_container().agent_service.chat(payload.message, payload.context_id)
    return AgentChatResponse.model_validate(response)


@router.post("/execute", response_model=AgentExecuteResponse)
async def execute(request: Request) -> AgentExecuteResponse:
    """执行一个自然语言描述的后端文档操作，支持 JSON 与模板上传。
    Execute a backend document operation described in natural language with JSON or template-upload inputs.
    """
    content_type = request.headers.get("content-type", "").lower()
    if "multipart/form-data" in content_type:
        payload = await _parse_multipart_execute_request(request)
    else:
        payload = AgentExecuteRequest.model_validate(await request.json()).model_dump()
        payload["template_name"] = None
        payload["template_content"] = None

    try:
        response = get_container().document_interaction_service.execute(
            message=payload["message"],
            document_ids=payload["document_ids"] or None,
            document_set_id=payload["document_set_id"],
            context_id=payload["context_id"],
            template_name=payload.get("template_name"),
            template_content=payload.get("template_content"),
            fill_mode=payload["fill_mode"],
            auto_match=payload["auto_match"],
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return AgentExecuteResponse.model_validate(response)


@router.get("/artifacts/{file_name}")
def download_artifact(file_name: str) -> FileResponse:
    """下载自然语言执行后生成的产物文件。    Download an artifact generated by agent execution."""

    if file_name != Path(file_name).name:
        raise HTTPException(status_code=400, detail="Invalid artifact file name.")

    outputs_dir = get_container().settings.outputs_dir.resolve()
    artifact_path = (outputs_dir / file_name).resolve()
    if artifact_path.parent != outputs_dir or not artifact_path.exists():
        raise HTTPException(status_code=404, detail="Artifact not found.")

    media_type = _guess_media_type(artifact_path.suffix.lower())
    return FileResponse(path=artifact_path, filename=file_name, media_type=media_type)


async def _parse_multipart_execute_request(request: Request) -> dict[str, object]:
    """解析 `agent/execute` 的 multipart 请求体。
    Parse the multipart request body used by `agent/execute`.
    """
    form = await request.form()
    message = str(form.get("message", "")).strip()
    if not message:
        raise HTTPException(status_code=400, detail="Missing execute message.")

    template_file = form.get("template_file")
    if template_file is not None and not isinstance(template_file, UploadFile):
        raise HTTPException(status_code=400, detail="Invalid template file payload.")

    template_content = await template_file.read() if template_file is not None else None
    return {
        "message": message,
        "context_id": _as_optional_string(form.get("context_id")),
        "document_ids": _parse_document_ids(form.get("document_ids")),
        "document_set_id": _as_optional_string(form.get("document_set_id")),
        "fill_mode": _as_optional_string(form.get("fill_mode")) or "canonical",
        "auto_match": _parse_bool(form.get("auto_match"), default=True),
        "template_name": template_file.filename if template_file is not None else None,
        "template_content": template_content,
    }


def _parse_document_ids(raw_value: object) -> list[str]:
    """解析 multipart 文本中的文档 id 列表。
    Parse a list of document ids from multipart text content.
    """
    if raw_value is None:
        return []
    text = str(raw_value).strip()
    if not text:
        return []
    if text.startswith("["):
        try:
            payload = json.loads(text)
        except json.JSONDecodeError as exc:
            raise HTTPException(status_code=400, detail="Invalid JSON in document_ids.") from exc
        if not isinstance(payload, list):
            raise HTTPException(status_code=400, detail="document_ids JSON must be a list.")
        return [str(item).strip() for item in payload if str(item).strip()]
    return [item.strip() for item in text.split(",") if item.strip()]


def _parse_bool(raw_value: object, *, default: bool) -> bool:
    """解析 multipart 表单中的布尔文本。
    Parse boolean-like multipart form text.
    """
    if raw_value is None:
        return default
    normalized = str(raw_value).strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise HTTPException(status_code=400, detail=f"Invalid boolean value: {raw_value}")


def _as_optional_string(raw_value: object) -> str | None:
    """将表单值规范化为可选字符串。
    Normalize a form value into an optional string.
    """
    if raw_value is None:
        return None
    text = str(raw_value).strip()
    return text or None


def _guess_media_type(suffix: str) -> str:
    """根据文件后缀推断下载内容类型。    Guess a download media type from a file suffix."""

    if suffix == ".docx":
        return "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    if suffix == ".xlsx":
        return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    if suffix == ".md":
        return "text/markdown; charset=utf-8"
    if suffix == ".txt":
        return "text/plain; charset=utf-8"
    if suffix == ".json":
        return "application/json"
    return "application/octet-stream"
