from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse

from app.core.container import get_container
from app.schemas.templates import TemplateFillAcceptedResponse

router = APIRouter()


@router.post("/suggest-documents")
async def suggest_documents(
    template_file: UploadFile = File(...),
    document_set_id: str | None = Form(default=None),
) -> dict:
    """分析模板并返回候选源文档供用户选择。
    Analyse a template and return candidate source documents for user selection.
    """
    if not template_file.filename:
        raise HTTPException(status_code=400, detail="Missing template file name.")
    content = await template_file.read()
    try:
        result = get_container().template_service.suggest_documents(
            template_name=template_file.filename,
            content=content,
            document_set_id=document_set_id,
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return result


@router.post("/fill", response_model=TemplateFillAcceptedResponse)
async def fill_template(
    template_file: UploadFile = File(...),
    document_set_id: str | None = Form(default="default"),
    fill_mode: str = Form(default="canonical"),
    document_ids: str | None = Form(default=None),
    auto_match: bool = Form(default=True),
    user_requirement: str = Form(default=""),
) -> TemplateFillAcceptedResponse:
    """上传模板工作簿并加入回填任务队列。
    Upload a template workbook and queue a fill task.
    """
    if not template_file.filename:
        raise HTTPException(status_code=400, detail="Missing template file name.")

    content = await template_file.read()
    parsed_document_ids = [item.strip() for item in (document_ids or "").split(",") if item.strip()]
    try:
        task = get_container().template_service.submit_fill_task(
            template_name=template_file.filename,
            content=content,
            fill_mode=fill_mode,
            document_set_id=document_set_id,
            document_ids=parsed_document_ids or None,
            auto_match=auto_match,
            user_requirement=user_requirement,
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    return TemplateFillAcceptedResponse(
        task_id=task.task_id,
        status=task.status,
        template_name=template_file.filename,
        document_set_id=document_set_id,
        auto_match=auto_match,
    )


@router.get("/result/{task_id}")
def download_result(task_id: str) -> FileResponse:
    """下载已完成任务生成的回填结果模板。
    Download the filled template generated by a completed task.
    """
    result = get_container().template_service.get_result(task_id)
    if result is None:
        raise HTTPException(status_code=404, detail="Filled template result not found.")
    suffix = Path(result.output_file_name).suffix.lower()
    media_type = (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        if suffix == ".docx"
        else "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )
    return FileResponse(
        path=result.output_path,
        filename=result.output_file_name,
        media_type=media_type,
    )
